### 200
GET http://localhost:8081/rest/v1/200
Content-Type: application/json


### 401
GET http://localhost:8081/rest/v1/401
Content-Type: application/json

### 403
GET http://localhost:8081/rest/v1/403
Content-Type: application/json

### 404
GET http://localhost:8081/rest/v1/404
Content-Type: application/json

### 333
GET http://localhost:8081/rest/v1/333
Content-Type: application/json
